name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-replica-set: test-rs
        mongodb-version: 5.0

    - name: Test
      run: |
        go run cmd/grpc_server/main.go -port 3002 & # Ports 3002 and 3003 hard-coded as per config in e2e_test.go
        go run cmd/grpc_server/main.go -port 3003 & # Two GRPC instances for the 2 different tests - sequential and parallel
        sleep 7 # wait for the above GRPC servers to spawn for testing
        go test e2e_test.go core.go

